/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "🌾 Farm": "🌾 农场",
    "⛏️ Ore Mine": "⛏️ 金属矿",
    "⛏️ Advanced Ore Mine": "⛏️ 高级金属矿",
    "⚡ Quick Start Guide": "⚡ 快速开始指南",
    "⚡ Production Chains": "⚡ 生产链",
    "⚡ Coal Power Plant": "⚡ 煤电厂",
    "☢️ Nuclear Reactor": "☢️ 核反应堆",
    "🎯 Getting Started": "🎯 入门",
    "💾 Use the": "💾 使用",
    "💾 Save/Load": "💾 保存/加载",
    "💾 Save Current Game": "💾 保存当前游戏",
    "📂 Load Saved Game": "📂 加载保存的游戏",
    "💡 Pro Tips": "💡 高级提示",
    "🏭 Sawmill": "🏭 锯木厂",
    "Save/Load": "保存/加载",
    "Scroll": "滚动",
    "Save / Load Game": "保存 / 加载游戏",
    "Resources:": "资源:",
    "Remove": "移除",
    "Red text": "红字",
    "Power Supply:": "电力供应:",
    "Load": "加载",
    "Right-Click": "右键点击",
    "Right clicking is a more convenient way to remove": "右键点击是一种更方便的删除方式",
    "Train": "火车",
    "Welcome to Hexamotive": "欢迎来到 六角帝国",
    "Trains:": "火车:",
    "Track": "轨道",
    "Tracks:": "轨道:",
    "Tracks placed:": "放置的轨道:",
    "Zoom:": "缩放:",
    "Zoom in and out": "放大和缩小",
    "Wooden Turtle": "木龟",
    "Start Building! 🚀": "开始建造! 🚀",
    "Drag": "拖动",
    "Click": "点击",
    "Click on a track or building to remove it.": "点击一个轨道或建筑来移除它。",
    "Core": "核心",
    "Core Buildings:": "核心建筑:",
    "Capacity:": "容量:",
    "Buildings": "建筑",
    "Basic Track": "基础轨道",
    "🏗️ Building System": "🏗️ 建造系统",
    "🏛️ Legacy Vault": "🏛️ 遗产金库",
    "🏛️ Hub": "🏛️ 枢纽",
    "🏛️ Advanced Hub": "🏛️ 高级枢纽",
    "Hub": "枢纽",
    "Hub Resources:": "枢纽资源:",
    "Quick remove items": "快速移除物品",
    "their cost": "它们的成本",
    "Terrain Matters:": "地形问题:",
    "Refine": "精炼",
    "refunds": "退还",
    "Select Train Type:": "选择火车类型:",
    "Select Track Type:": "选择轨道类型:",
    "Selected Building": "已选择建筑",
    "Smart Routing:": "智能路由:",
    "Special Buildings:": "特殊建筑:",
    "🏢 Click on buildings to see their inventory and production status": "🏢 点击建筑物查看它们的库存和生产状态",
    "🏦 Investment Research Institute": "🏦 投资研究所",
    "💨 Wind Turbine": "💨 风力发电机",
    "💨 Windmill": "💨 风车",
    "💰 Commodity Exchange": "💰 商品交易所",
    "🔋 Some trains need power - build generators to keep them running": "🔋 有些火车需要电力——建造发电机来保持它们的运行",
    "🔥 Advanced Coal Mine": "🔥 高级煤矿",
    "🔥 Coal Mine": "🔥 煤矿",
    "🔥 Smelter": "🔥 冶炼厂",
    "🔩 Advanced Steel Mill": "🔩 高级炼钢厂",
    "🔩 Steel Mill": "🔩 炼钢厂",
    "🖱️ Controls": "🖱️ 控制",
    "🗑️ Removing buildings/tracks": "🗑️ 拆除建筑物/轨道",
    "🪨 Quarry": "🪨 采石场",
    "🪵 Lumberyard": "🪵 伐木场",
    "🚂 Railway System": "🚂 铁路系统",
    "🚂 Sputtering Pack Dog": "🚂 溅射包狗",
    "🚅 Electric Elephant": "🚅 电子大象",
    "🚅 Supercharged Caffeinated Megahauler": "🚅 超级咖啡因运输车",
    "🚆 Steam Dragon": "🚆 蒸汽巨龙",
    "🚉 Train Depot": "🚉 火车站",
    "🛞 Wooden Turtle": "🛞 木龟",
    "🛤️ Basic Track": "🛤️ 基础轨道",
    "A Hexagonal Transportation & Logistics Empire": "一个由六变形地块组成的运输和物流帝国",
    "All hubs share a common resource pool shown in the top-right": "所有枢纽共享一个公共资源池，如右上方所示",
    "Automatically pick up and deliver resources": "自动提取和交付资源",
    "Build extractors (farms, mines) near your hub": "在你的枢纽附近建造采掘点（农场、矿山）",
    "Build production chains, transport resources, and expand your network": "建立生产链，运输资源，扩大网络",
    "Buildings can only be placed on compatible terrain types": "建筑只能放置在兼容的地形类型上",
    "Buildings consume inputs to produce more outputs": "建筑消耗投入以产生更多产出",
    "Buildings produce resources → stored in their output inventory": "建筑生产资源→储存在它们的输出库存中",
    "button (bottom-left) to preserve your progress": "按钮（左下）保存您的进度",
    "Cargo Capacity: 10 units": "载货量：10个",
    "Connect them with tracks (click hex edges)": "将它们与轨道连接（点击十六进制边缘）",
    "Deploy trains to transport resources": "部署火车来运输资源",
    "Resources get spent from your hubs to allow you to build other things. Deliver resources to hubs with trains": "资源从你的枢纽消耗，让你建造其他的东西。用火车向枢纽输送资源",
    "Drag to move | Scroll to zoom | Click edges to place tracks": "拖动以移动|滚动以缩放|单击边缘以放置轨道",
    "Each train has a cargo limit - plan accordingly": "每列火车都有相应的载货限制计划",
    "Expand and unlock new buildings!": "扩展并解锁新建筑！",
    "Extract": "提取",
    "First Hub:": "第一个枢纽：",
    "Gather raw materials from terrain": "从地形上收集原材料",
    "Happens at the midpoint of each track segment": "发生在每个轨道段的中点",
    "High-tech buildings requiring electricity": "需要电力的高科技建筑",
    "Hubs for storage and distribution": "用于存储和分发的枢纽",
    "in costs means you can't afford it yet": "成本太高意味着你还负担不起",
    "Keep production flowing to unlock new technologies!": "保持生产流动，解锁新技术！",
    "No resources yet": "暂无资源",
    "No saved games yet": "暂无保存游戏",
    "Pan the camera around": "移动镜头",
    "Pickup/Delivery:": "提货/送货：",
    "Place buildings, tracks, trains": "放置建筑物、轨道、火车",
    "Place on hex edges to connect buildings (Cost: 1 ore each)": "放置在六角地块边缘连接建筑（每个消耗1矿石）",
    "Place your free hub on grass or sand": "把你的免费枢纽放在草地或沙滩上",
    "Power Demand:": "电力需求:",
    "Powered": "电力",
    "Process materials into advanced goods": "将材料加工成先进产品",
    "Rail System": "铁路系统",
    "These guys are slow and don't carry much, but they will get you started.": "这些家伙行动缓慢，携带的东西也不多，但他们会让你开始行动。",
    "Trains deliver to buildings that need those inputs (or to hubs)": "火车运送到需要这些输入的建筑物（或枢纽）。",
    "Trains pick up from outputs when passing by": "火车经过时，会从输出的货物中获益",
    "Trains randomly choose paths at junctions": "列车在路口随机选择路径",
    "Your first hub is FREE and comes with starter resources (wood, grain, ore)": "你的第一个枢纽是免费的，并附带入门资源（木材，谷物，矿石）",
    "⚠️ Cannot be removed": "⚠️无法移除",
    "grain:": "谷物:",
    "Inputs:": "输入:",
    "ore:": "铁矿石:",
    "Production Progress": "生产进度",
    "wood:": "木头:",
    "Lumberyard": "伐木场",
    "Farm": "农场",
    "produces grain (as with all other buildings that produce things, use trains to pick up)": "生产谷物（和其他生产物品的建筑一样，使用火车来拾取）",
    "Advanced Coal Mine": "高级煤矿",
    "Advanced Hub": "高级枢纽",
    "Advanced Ore Mine": "高级金属矿",
    "Advanced Steel Mill": "高级钢厂",
    "Automated mining operations. Requires power.": "自动化采矿作业。需要电力。",
    "Burns coal to generate massive power. 10x more efficient than wind.": "燃烧煤来产生大量的电力。比风能效率高10倍。",
    "Coal Mine": "煤矿",
    "Coal Power Plant": "火力发电厂",
    "Commodity Exchange": "商品交易所",
    "Cutting-edge smelting technology. Processes ore directly into steel. Requires power.": "先进的冶炼技术。把矿石直接加工成钢。需要电力。",
    "Industrial coal extraction. Requires power.": "工业煤炭开采。需要电力。",
    "Investment Research Institute": "投资研究所",
    "Legacy Vault": "遗产库",
    "Massive storage facility. 50x capacity of standard hub.": "大规模存储设施。容量是标准枢纽的50倍。",
    "Nuclear Reactor": "核反应堆",
    "Produces: (totalGold) => Math.round(totalGold * 0.05) gold": "产生：(总计黄金) => Math.round(总计黄金 * 0.05）黄金",
    "Quarry": "采石场",
    "Research new investment strategies. Compounds your gold reserves.": "研究新的投资策略。增加你的黄金储备。",
    "Sawmill": "锯木厂",
    "Sell resources for gold.": "出售资源换取黄金。",
    "Smelter": "冶炼厂",
    "Steel Mill": "炼钢厂",
    "stone:": "石头：",
    "The ultimate achievement. Preserve your legacy for eternity.": "最终的成就。将你的遗产保存到永恒。",
    "The ultimate power source. Generates tremendous energy.": "终极能量来源。产生巨大的能量。",
    "Train Depot": "火车站",
    "Use this building for managing trains.": "用这个建筑来管理火车。",
    "Wind Turbine": "风力发电机",
    "Windmill": "风车",
    "planks:": "木板:",
    "Ore Mine": "金属矿",
    "Outputs:": "输出:",
    "iron:": "铁:",
    "Sputtering Pack Dog": "溅射包狗",
    "Pretty fast, but still don't carry much": "速度很快，但还是带不了多少东西",
    "🚂 Train Summary": "🚂 火车概览",
    "Remove All": "全部移除",
    "coal:": "煤:",
    "flour:": "面粉:",
    "steel:": "钢:",
    "Please enter a save name": "请输入一个存档名称",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "%": "%",
    "×": "×",
    "✋": "✋",
    "❌": "❌",
    "❓": "❓",
    "⬡": "⬡",
    "⚡": "⚡",
    "⛏️": "⛏️",
    "🏗️": "🏗️",
    "🏭": "🏭",
    "🏢": "🏢",
    "🏛️": "🏛️",
    "🔴": "🔴",
    "🔍": "🔍",
    "🖱️": "🖱️",
    "👆": "👆",
    "🛤️": "🛤️",
    "🛞": "🛞",
    "🚆": "🚆",
    "🚂": "🚂",
    "🌾": "🌾",
    "🪵": "🪵",
    "☢️": "☢️",
    "🏦": "🏦",
    "💨": "💨",
    "💰": "💰",
    "🔥": "🔥",
    "🔩": "🔩",
    "🪨": "🪨",
    "🚉": "🚉",
    "📏": "📏",
    "📦": "📦",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Storage: ": "存储: ",
    "Location: ": "位置: ",
    "Game saved as ": "游戏已保存为 ",
    "Deleted ": "已删除 ",
    "Loaded ": "已加载 ",
    "Description: ": "介绍: ",
    "At capacity: ": "容量在: ",
    "Available: ": "可用: ",
    "Total: ": "总计: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "Trains can be removed from a Train Depot Building": "火车可以在火车站建筑删除",
    "Removed buildings and tracks will refund building costs to your hubs.": "被移除的建筑和轨道将会把建造成本退还给你的枢纽。",
    " - Basic Resources:": " - 基础资源:",
    " (Refine):": " (精炼):",
    " (Extract):": " (提取):",
    " (Powered):": " (供电):",
    " - Processing:": " - 处理中:",
    " - Advanced:": " - 高级:",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) • (.+) tracks • (.+) trains • (.+) buildings$/, '$1 • $2 轨道 • $3 火车 • $4 建筑'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) ore$/, '$1 矿石'],
    [/^([\d\.,]+) ore,$/, '$1 矿石,'],
    [/^([\d\.,]+) grain$/, '$1 谷物'],
    [/^([\d\.,]+) grain,$/, '$1 谷物,'],
    [/^, ([\d\.,]+) wood, ([\d\.,]+) flour$/, '$1 木头, $2 面粉'],
    [/^, ([\d\.,]+) ore, ([\d\.,]+) stone$/, '$1 矿石, $2 石头'],
    [/^, ([\d\.,]+) stone, ([\d\.,]+) grain$/, '$1 石头, $2 谷物'],
    [/^, ([\d\.,]+) planks, ([\d\.,]+) flour$/, '$1 木板, $2 面粉'],
    [/^([\d\.,]+) iron, ([\d\.,]+) planks$/, '$1 铁, $2 木板'],
    [/^([\d\.,]+) grain, ([\d\.,]+) wood$/, '$1 谷物, $2 木头'],
    [/^([\d\.,]+) ore, ([\d\.,]+) wood,$/, '$1 矿石, $2 木头,'],
    [/^([\d\.,]+) grain, ([\d\.,]+) wood,$/, '$1 谷物, $2 木头,'],
    [/^([\d\.,]+) grain, ([\d\.,]+) wood, ([\d\.,]+) ore,$/, '$1 谷物, $2 木头, $3 矿石,'],
    [/^([\d\.,]+) grain, ([\d\.,]+) wood, ([\d\.,]+) stone$/, '$1 谷物, $2 木头, $3 石头'],
    [/^([\d\.,]+) wood, ([\d\.,]+) stone, ([\d\.,]+) grain$/, '$1 木头, $2 石头, $3 谷物'],
    [/^([\d\.,]+) stone, ([\d\.,]+) iron, ([\d\.,]+) planks$/, '$1 石头, $2 铁, $3 木板'],
    [/^([\d\.,]+) grain, ([\d\.,]+) wood, ([\d\.,]+) ore, ([\d\.,]+) stone$/, '$1 谷物, $2 木头, $3 矿石, $4 石头'],
    [/^([\d\.,]+) wood$/, '$1 木头'],
    [/^([\d\.,]+) wood,$/, '$1 木头,'],
    [/^([\d\.,]+) iron$/, '$1 铁'],
    [/^([\d\.,]+) planks$/, '$1 木板'],
    [/^([\d\.,]+) stone$/, '$1 石头'],
    [/^([\d\.,]+) stone,$/, '$1 石头,'],
    [/^([\d\.,]+) steel$/, '$1 钢'],
    [/^([\d\.,]+) flour$/, '$1 面粉'],
    [/^([\d\.,]+) gold$/, '$1 黄金'],
    [/^, ([\d\.,]+) ore$/, ', $1 矿石'],
    [/^, ([\d\.,]+) stone,$/, ', $1 石头,'],
    [/^, ([\d\.,]+) ore,$/, ', $1 矿石,'],
    [/^, ([\d\.,]+) grain$/, ', $1 谷物'],
    [/^, ([\d\.,]+) wood$/, ', $1 木头'],
    [/^, ([\d\.,]+) wood,$/, ', $1 木头,'],
    [/^, ([\d\.,]+) wood, ([\d\.,]+) ore,$/, ', $1 木头, $2 矿石,'],
    [/^, ([\d\.,]+) iron, ([\d\.,]+) planks$/, ', $1 铁, $2 木板'],
    [/^, ([\d\.,]+) iron$/, ', $1 铁'],
    [/^, ([\d\.,]+) planks$/, ', $1 木板'],
    [/^, ([\d\.,]+) planks,$/, ', $1 木板,'],
    [/^, ([\d\.,]+) stone$/, ', $1 石头'],
    [/^, ([\d\.,]+) steel$/, ', $1 钢'],
    [/^, ([\d\.,]+) flour$/, ', $1 面粉'],
    [/^, ([\d\.,]+) gold$/, ', $1 黄金'],
    [/^📦 grain: ([\d\.,]+)$/, '📦 谷物: $1'],
    [/^📦 ore: ([\d\.,]+)$/, '📦 矿石: $1'],
    [/^📦 wood: ([\d\.,]+)$/, '📦 木头: $1'],
    [/^📦 coal: ([\d\.,]+)$/, '📦 煤: $1'],
    [/^📦 iron: ([\d\.,]+)$/, '📦 铁: $1'],
    [/^📦 planks: ([\d\.,]+)$/, '📦 木板: $1'],
    [/^📦 stone: ([\d\.,]+)$/, '📦 石头: $1'],
    [/^📦 steel: ([\d\.,]+)$/, '📦 钢: $1'],
    [/^📦 flour: ([\d\.,]+)$/, '📦 面粉: $1'],
    [/^ore: ([\d\.,]+), wood: ([\d\.,]+), grain: ([\d\.,]+), iron: ([\d\.,]+)$/, '矿石: $1, 木头: $2, 谷物: $3, 铁: $4'],
    [/^ore: ([\d\.,]+), wood: ([\d\.,]+), grain: ([\d\.,]+), iron: ([\d\.,]+), coal: ([\d\.,]+), steel: ([\d\.,]+), stone: ([\d\.,]+), flour: ([\d\.,]+), planks: ([\d\.,]+)$/, '矿石: $1, 木头: $2, 谷物: $3, 铁: $4, 煤: $5, 钢: $6, 石头: $7, 面粉: $8, 木板: $9'],
    [/^Consumes: ([\d\.,]+) grain$/, '消耗: $1 谷物'],
    [/^Consumes: ([\d\.,]+) coal$/, '消耗: $1 煤'],
    [/^Consumes: ([\d\.,]+) stone$/, '消耗: $1 石头'],
    [/^Consumes: ([\d\.,]+) ore$/, '消耗: $1 矿石'],
    [/^Consumes: ([\d\.,]+) wood$/, '消耗: $1 木头'],
    [/^Consumes: ([\d\.,]+) iron$/, '消耗: $1 铁'],
    [/^Consumes: ([\d\.,]+) iron, ([\d\.,]+) coal$/, '消耗: $1 铁, $2 煤'],
    [/^Consumes: ([\d\.,]+) planks$/, '消耗: $1 木板'],
    [/^Consumes: ([\d\.,]+) steel$/, '消耗: $1 钢'],
    [/^Consumes: ([\d\.,]+) flour$/, '消耗: $1 面粉'],
    [/^Consumes: ([\d\.,]+)x grain$/, '消耗: $1x 谷物'],
    [/^Consumes: ([\d\.,]+)x coal$/, '消耗: $1x 煤'],
    [/^Consumes: ([\d\.,]+)x stone$/, '消耗: $1x 石头'],
    [/^Consumes: ([\d\.,]+)x ore$/, '消耗: $1x 矿石'],
    [/^Consumes: ([\d\.,]+)x wood$/, '消耗: $1x 木头'],
    [/^Consumes: ([\d\.,]+)x iron$/, '消耗: $1x 铁'],
    [/^Consumes: ([\d\.,]+)x planks$/, '消耗: $1x 木板'],
    [/^Consumes: ([\d\.,]+)x steel$/, '消耗: $1x 钢'],
    [/^Consumes: ([\d\.,]+)x flour$/, '消耗: $1x 面粉'],
    [/^Produces: ([\d\.,]+) grain$/, '生产: $1 谷物'],
    [/^Produces: ([\d\.,]+) coal$/, '生产: $1 煤'],
    [/^Produces: ([\d\.,]+) stone$/, '生产: $1 石头'],
    [/^Produces: ([\d\.,]+) ore$/, '生产: $1 矿石'],
    [/^Produces: ([\d\.,]+) wood$/, '生产: $1 木头'],
    [/^Produces: ([\d\.,]+) iron$/, '生产: $1 铁'],
    [/^Produces: ([\d\.,]+) planks$/, '生产: $1 木板'],
    [/^Produces: ([\d\.,]+) steel$/, '生产: $1 钢'],
    [/^Produces: ([\d\.,]+) flour$/, '生产: $1 面粉'],
    [/^flour: ([\d\.,]+)$/, '面粉: $1'],
    [/^steel: ([\d\.,]+)$/, '钢: $1'],
    [/^planks: ([\d\.,]+)$/, '木板: $1'],
    [/^planks: ([\d\.,]+), wood: ([\d\.,]+)$/, '木板: $1, 木头: $2'],
    [/^steel: ([\d\.,]+), ore: ([\d\.,]+)$/, '钢: $1, 矿石: $2'],
    [/^iron: ([\d\.,]+), ore: ([\d\.,]+)$/, '铁: $1, 矿石: $2'],
    [/^flour: ([\d\.,]+), grain: ([\d\.,]+)$/, '面粉: $1, 谷物: $2'],
    [/^stone: ([\d\.,]+)$/, '石头: $1'],
    [/^iron: ([\d\.,]+)$/, '铁: $1'],
    [/^ore: ([\d\.,]+)$/, '矿石: $1'],
    [/^coal: ([\d\.,]+)$/, '煤: $1'],
    [/^grain: ([\d\.,]+)$/, '谷物: $1'],
    [/^wood: ([\d\.,]+)$/, '木头: $1'],
    [/^Produces: ([\d\.,]+) wood$/, '生产: $1 木头'],
    [/^Produces: ([\d\.,]+) grain$/, '生产: $1 谷物'],
    [/^Tier ([\d\.,]+)$/, '层级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Speed: ([\d\.,]+)$/, '速度: $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Speed: (.+) units\/s$/, '速度：$1 单位/秒'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);
